---
- include: dependencies/{{ ansible_distribution | lower | replace(' ', '') }}.yml
  tags:
    - install
    - deps

- name: Copy cloud.cfg
  template:
    src: cloud.cfg
    dest: /etc/cloud/cloud.cfg

- name: Clean up cloud-init dir
  file:
    state: absent
    path: /var/lib/cloud/
