---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Check cloud-init status
    command: cloud-init status
    register: command_result
    changed_when: false
    failed_when: "command_result.stdout != 'status: not run'" # Implies a fresh install
